# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.0.13.dev0+g9fbd6e2.d20230610'
__version_tuple__ = version_tuple = (0, 0, 13, 'dev0', 'g9fbd6e2.d20230610')
