# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.0.7.dev2+g47c0965.d20230607'
__version_tuple__ = version_tuple = (0, 0, 7, 'dev2', 'g47c0965.d20230607')
